apiVersion: v2
name: lib-configuration
description: Configmap and Secrets utils for Youwol
type: library
version: 0.0.2

dependencies:
  - name: lib-utils
    version: 0.0.1
    repository: https://gitlab.com/api/v4/projects/15166395/packages/helm/stable/
